export interface Exemplar {
  id: string;
  label: string;
  description: string;
  text: string;
}

export const EXEMPLARS: Exemplar[] = [
  {
    id: 'solo-criminal',
    label: 'Solo Criminal Defense',
    description: 'DUI, drug offenses, assault, property crimes, juvenile',
    text: [
      'Criminal Defense',
      '\tDUI & Impaired Driving',
      '\t\tDriving Under the Influence',
      '\t\tBoating DUI/BUI',
      '\tDrug Offenses',
      '\t\tCannabis Law',
      '\t\tControlled Substance Charges',
      '\tViolent Crimes',
      '\t\tAssault Law',
      '\t\tDomestic Violence',
      '\tProperty Crimes',
      '\t\tBurglary',
      '\t\tShoplifting',
      '\tJuvenile & Financial Crimes',
      '\t\tJuvenile Law',
      '\t\tWire Fraud',
    ].join('\n'),
  },
  {
    id: 'family-law',
    label: 'Family Law Firm',
    description: 'Divorce, custody, support, adoption, protective orders',
    text: [
      'Family Law',
      '\tDivorce & Separation',
      '\t\tContested Divorce',
      '\t\tLegal Separation',
      '\tChild Custody',
      '\t\tCustody Law',
      '\t\tParenting Plan',
      '\tSupport Obligations',
      '\t\tChild Support',
      '\t\tSpousal Support',
      '\tProtective Orders',
      '\t\tRestraining Order',
      '\t\tCriminal Harassment',
      '\tAdoption & Guardianship',
      '\t\tAdoption',
      '\t\tGuardianship',
    ].join('\n'),
  },
  {
    id: 'personal-injury',
    label: 'Personal Injury Plaintiff',
    description: 'Auto accidents, premises liability, med mal, product liability, mass torts',
    text: [
      'Personal Injury',
      '\tMotor Vehicle Accidents',
      '\t\tMotor Vehicle Law',
      '\t\tAccident Benefits Law',
      '\tPremises Liability',
      '\t\tSlip-and-Fall Negligence',
      '\t\tDog Bite',
      '\tMedical Malpractice',
      '\t\tMedical Malpractice',
      '\t\tWrongful Death Claim',
      '\tProduct Liability',
      '\t\tProduct Liability Law',
      '\t\tDefective Product Claims',
      '\tMass Torts & Defamation',
      '\t\tMass Torts Law',
      '\t\tDefamation Law',
    ].join('\n'),
  },
  {
    id: 'employment-labor',
    label: 'Employment & Labor',
    description: 'Discrimination, wage & hour, workplace safety, termination, benefits',
    text: [
      'Employment Law',
      '\tDiscrimination',
      '\t\tEmployment Discrimination Law',
      '\t\tAge Discrimination',
      '\tWage & Hour',
      '\t\tWage and Hour Law',
      '\t\tPay Equity Law',
      '\tWorkplace Safety',
      '\t\tEmployment Health and Safety Law',
      '\t\tSubstance Abuse and Drug Testing Law',
      '\tWrongful Termination',
      '\t\tWrongful Discharge or Termination',
      '\t\tReduction in Force Law',
      '\tBenefits & Compensation',
      '\t\tWorkers Compensation Law',
      '\t\tUnemployment Benefits Law',
    ].join('\n'),
  },
  {
    id: 'corporate-ma',
    label: 'Corporate M&A',
    description: 'Governance, securities, due diligence, deal structuring, antitrust',
    text: [
      'Mergers & Acquisitions',
      '\tCorporate Governance',
      '\t\tCorporate Governance Law',
      '\t\tBreach of Fiduciary Duty',
      '\tSecurities',
      '\t\tSecurity Offerings and Capital Markets Law',
      '\t\tSecurities Fraud',
      '\tDue Diligence',
      '\t\tAsset Due Diligence Practice',
      '\t\tRegulatory Compliance',
      '\tDeal Structuring',
      '\t\tStock Purchase Agreement',
      '\t\tAsset Purchase Agreement',
      '\tPost-Merger',
      '\t\tAntitrust and Competition Law',
      '\t\tHostile Takeover',
    ].join('\n'),
  },
  {
    id: 'ip-tech',
    label: 'IP & Technology',
    description: 'Patents, trademarks, trade secrets, copyright, IP transactions',
    text: [
      'Intellectual Property',
      '\tPatent Practice',
      '\t\tPatent Law',
      '\t\tPatent Infringement',
      '\tTrademark Practice',
      '\t\tTrademark and Trade Dress Law',
      '\t\tTrademark Infringement',
      '\tTrade Secrets',
      '\t\tTrade Secret Law',
      '\t\tTrade Secret Misappropriation',
      '\tCopyright Practice',
      '\t\tCopyright Law',
      '\t\tCopyright Infringement',
      '\tIP Transactions',
      '\t\tIntellectual Property Assets',
      '\t\tSoftware Patent',
    ].join('\n'),
  },
  {
    id: 'commercial-lit',
    label: 'Commercial Litigation',
    description: 'Contracts, antitrust, securities, consumer protection, arbitration',
    text: [
      'Complex Commercial Litigation',
      '\tContract Disputes',
      '\t\tBreach of Contract',
      '\t\tTortious Interference Claims',
      '\tAntitrust',
      '\t\tAntitrust and Competition Law',
      '\t\tAntitrust - Bid-Rigging Claims',
      '\tSecurities Litigation',
      '\t\tSecurities Fraud',
      '\t\tInsider Trading',
      '\tConsumer & Trade',
      '\t\tConsumer Protection Law',
      '\t\tUnfair Competition',
      '\tDispute Resolution',
      '\t\tArbitration Practice',
      '\t\tMediation Practice',
    ].join('\n'),
  },
  {
    id: 'real-estate',
    label: 'Real Estate',
    description: 'Property transactions, landlord-tenant, zoning, construction, foreclosure',
    text: [
      'Real Property Law',
      '\tProperty Transactions',
      '\t\tProperty Rights and Transactions Law',
      '\t\tClearing Title',
      '\tLandlord-Tenant',
      '\t\tLandlord Tenant Law',
      '\t\tLease Agreements',
      '\tZoning & Land Use',
      '\t\tLand Use and Zoning Law',
      '\t\tZoning Variance',
      '\tConstruction',
      '\t\tConstruction and Development Law',
      '\t\tBuilding Code Violations',
      '\tForeclosure & Liens',
      '\t\tMortgage Foreclosure',
      '\t\tEminent Domain Law',
    ].join('\n'),
  },
  {
    id: 'banking-finance',
    label: 'Banking & Finance',
    description: 'Lending, securities, investment funds, structured finance, crypto',
    text: [
      'Banking & Finance Law',
      '\tCommercial Lending',
      '\t\tCommercial Finance Law',
      '\t\tAsset-Based Lending Practice',
      '\tSecurities & Capital Markets',
      '\t\tBroker-Dealer Law',
      '\t\tDerivatives and Futures Law',
      '\tInvestment Funds',
      '\t\tInvestment Companies Law',
      '\t\tPrivate Equity, Hedge Funds and Venture Capital Law',
      '\tStructured Finance',
      '\t\tStructured Finance Law',
      '\t\tCollateralized Loan Obligation',
      '\tCompliance & Enforcement',
      '\t\tBank Secrecy and Anti-Money Laundering Law',
      '\t\tCryptocurrency Law',
    ].join('\n'),
  },
  {
    id: 'immigration',
    label: 'Immigration',
    description: 'Visas, asylum, deportation, naturalization, employment immigration',
    text: [
      'Immigration Law',
      '\tEmployment Visas',
      '\t\tEmployment Immigration Law',
      '\t\tH-1B Visa',
      '\tFamily & Humanitarian',
      '\t\tAffirmative Asylum',
      '\t\tRefugee',
      '\tRemoval Defense',
      '\t\tDeportation',
      '\t\tDefensive Asylum',
      '\tStatus Adjustment',
      '\t\tNaturalization Application',
      '\t\tGreen Card',
      '\tSpecial Visas',
      '\t\tStudent Visa',
      '\t\tEntertainment Visa',
    ].join('\n'),
  },
];
