export interface Exemplar {
  id: string;
  label: string;
  description: string;
  text: string;
}

export const EXEMPLARS: Exemplar[] = [
  {
    id: 'solo-criminal',
    label: 'Solo Criminal Defense',
    description: 'DUI, drug offenses, violent crimes, property crimes, juvenile',
    text: [
      'Criminal Defense',
      '\tDUI / Impaired Driving',
      '\t\tFirst Offense DUI',
      '\t\tCommercial Vehicle DUI',
      '\tDrug Offenses',
      '\t\tDrug Possession',
      '\t\tDrug Trafficking',
      '\tViolent Crimes',
      '\t\tAssault & Battery',
      '\t\tDomestic Violence',
      '\tProperty Crimes',
      '\t\tTheft & Shoplifting',
      '\t\tBurglary',
      '\tJuvenile Offenses',
      '\t\tJuvenile Drug Charges',
    ].join('\n'),
  },
  {
    id: 'family-law',
    label: 'Family Law Firm',
    description: 'Divorce, custody, support, adoption, protective orders',
    text: [
      'Family Law',
      '\tDivorce & Separation',
      '\t\tContested Divorce',
      '\t\tMediated Divorce',
      '\tChild Custody',
      '\t\tJoint Custody Arrangement',
      '\t\tCustody Modification',
      '\tChild Support',
      '\t\tSupport Calculation',
      '\t\tSupport Enforcement',
      '\tAdoption',
      '\t\tStepparent Adoption',
      '\t\tInternational Adoption',
      '\tDomestic Violence Protection',
      '\t\tRestraining Orders',
    ].join('\n'),
  },
  {
    id: 'personal-injury',
    label: 'Personal Injury Plaintiff',
    description: 'Auto accidents, premises liability, med mal, products, workers comp',
    text: [
      'Personal Injury',
      '\tMotor Vehicle Accidents',
      '\t\tRear-End Collision',
      '\t\tTrucking Accident',
      '\tPremises Liability',
      '\t\tSlip and Fall',
      '\t\tNegligent Security',
      '\tMedical Malpractice',
      '\t\tSurgical Error',
      '\t\tMisdiagnosis',
      '\tProduct Liability',
      '\t\tDefective Consumer Product',
      '\t\tPharmaceutical Injury',
      '\tWorkers\' Compensation',
      '\t\tWorkplace Injury Claim',
    ].join('\n'),
  },
  {
    id: 'employment-labor',
    label: 'Employment & Labor',
    description: 'Discrimination, wage & hour, OSHA, executive, gov contractor',
    text: [
      'Employment Litigation',
      '\tDiscrimination Claims',
      '\t\tTitle VII Race Discrimination',
      '\t\tADA Disability Accommodation',
      '\tWage & Hour Disputes',
      '\t\tFLSA Overtime Claims',
      '\t\tTip Credit Violations',
      '\tWorkplace Safety',
      '\t\tOSHA Violation Defense',
      '\t\tWorkers\' Comp Subrogation',
      '\tExecutive Employment',
      '\t\tNon-Compete Litigation',
      '\t\tSeverance Negotiation',
      '\tGovernment Contractor Compliance',
      '\t\tAffirmative Action Plan',
    ].join('\n'),
  },
  {
    id: 'corporate-ma',
    label: 'Corporate M&A',
    description: 'Buy-side, sell-side, due diligence, structuring, integration',
    text: [
      'Mergers & Acquisitions',
      '\tBuy-Side Advisory',
      '\t\tStrategic Acquisition',
      '\t\tPrivate Equity Buyout',
      '\tSell-Side Advisory',
      '\t\tCorporate Divestiture',
      '\t\tManagement Buyout',
      '\tDue Diligence',
      '\t\tFinancial Due Diligence',
      '\t\tRegulatory Due Diligence',
      '\tTransaction Structuring',
      '\t\tStock Purchase Agreement',
      '\t\tAsset Purchase Agreement',
      '\tPost-Merger Integration',
      '\t\tAntitrust Compliance',
    ].join('\n'),
  },
  {
    id: 'ip-tech',
    label: 'IP & Technology',
    description: 'Patents, trademarks, trade secrets, copyright, licensing',
    text: [
      'Intellectual Property',
      '\tPatent Practice',
      '\t\tPatent Prosecution',
      '\t\tPatent Litigation',
      '\tTrademark Practice',
      '\t\tTrademark Registration',
      '\t\tTrademark Infringement',
      '\tTrade Secrets',
      '\t\tTrade Secret Litigation',
      '\t\tNon-Compete Enforcement',
      '\tCopyright Practice',
      '\t\tCopyright Registration',
      '\t\tDigital Content Licensing',
      '\tIP Transactions',
      '\t\tTechnology Licensing',
    ].join('\n'),
  },
  {
    id: 'commercial-lit',
    label: 'Commercial Litigation',
    description: 'Securities, antitrust, contracts, class actions, gov investigations',
    text: [
      'Complex Commercial Litigation',
      '\tSecurities Litigation',
      '\t\tSecurities Fraud Class Action',
      '\t\tShareholder Derivative Suit',
      '\tAntitrust Litigation',
      '\t\tPrice-Fixing Conspiracy',
      '\t\tMonopolization Claims',
      '\tContract Disputes',
      '\t\tBreach of Contract',
      '\t\tTortious Interference',
      '\tClass Action Defense',
      '\t\tConsumer Class Action',
      '\t\tProduct Liability Mass Tort',
      '\tGovernment Investigations',
      '\t\tSEC Enforcement Defense',
    ].join('\n'),
  },
];
